### PR TITLE
Use dependabot grouping instead of custom GH action

### PR DESCRIPTION
**Pull request by StefMa**
Just a small improvement, I guess ...

### CODE REVIEW

**Comment by StefMa** [comment]
Hey @alextu ,

would you be interested in this? ☺
I just thought it make more sense as the other merge action. Merging any dependency update into a single PR may lead to other problems and doesn't look right to me 😅.

Just let me know, if not x, I will close it 🙃.

**Comment by alextu** [comment]
Hey, thanks for your suggestion, I'm not familiar with this feature, I'll look into it and let you know :)

**Comment by StefMa** [comment]
By default, dependabot will create a new pull request for each single dependency update.
Sometimes this is not the desired behavior.

 Take the example with Jackson here. Both artifacts will always be updated together (by the publisher). In this case, with grouping enabled, dependabot will only create a single PR with both dependencies updated.

However, what the combine PR action you used before will simply merge all of your dependabot PRs into a single one. Which I think is also not the desired behavior. Because not all dependencies "belong" to each other and it is worth to have a separate commit history for these. This is not the case with the combining PR.

Hope this helps a bit 🙃

**Review by alextu — APPROVED** [review]

**Comment by alextu** [comment]
@StefMa Sorry for the late response, could you please resolve the conflict so we can merge it ?

**Review by alextu — APPROVED** [review]

**Pull request merged**
